version: '3.1'

volumes:
    pgsql-data: {}
    public-assets: {}

services:
    php:
        build: .docker/php-fpm
        container_name: web-multiapp
        volumes:
            - .:/var/www/symfony:delegated
            - ./var/logs/symfony:/var/www/symfony/var/logs:cached
        extra_hosts:
            - "docker.host:127.0.0.1"
    nginx:
        build: .docker/nginx
        container_name: nginx-multiapp
        ports:
            - "80:80"
        links:
            - php
        volumes:
            - ./.docker/logs/nginx/:/var/log/nginx:cached
            - ./public:/var/www/symfony/public:cached
